### ISSUE TITLE
[AND] 아카이빙 화면 구현 및 상태 관리

### ISSUE THREAD

**Issue by SeungWoo-Ahn** [softeerbootcamp-2nd/H9-88Hey#101]
# 🕹️ 기능 설명
* 아카이빙 화면들을 구현한다
* 아카이빙 화면들의 상태 관리를 구현한다

# 📌 TO-DO
- [x] 아카이빙 메인 화면 구현과 상태 관리
- [x] 아카이빙 차량 검색 BottomSheet 구현과 상태 관리
- [x] 아카이빙 상세 화면 구현과 상태 관리
- [x] UI 보완
    - [x] 태그에 밀리는 태그 개수 Text 보완
    - [x] 선택된 옵션 태그가 앞으로 오도록 수정
