### ISSUE TITLE
[AND] 아카이빙 네트워크 연결

### ISSUE THREAD

**Issue by SeungWoo-Ahn** [softeerbootcamp-2nd/H9-88Hey#103]
# 🕹️ 기능 설명
* 아카이빙 화면들의 데이터를 서버와 연결한다

# 📌 TO-DO
- [x] 아카이빙 메인 화면 연결
- [x] 아카이빙 차량 검색 BottomSheet 연결
- [x] 아카이빙 상세 화면 연결
