### ISSUE TITLE
[AND] 내차만들기 UI 보완

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#125]
# ✏️ 계획 설명
* 내차만들기 화면 진행이 어색하지 않도록 개선한다.

# 📌 TO-DO
- [x] Back button 입력 시 screen progress 올바르게 처리
- [x] 360도 이미지 현재 이미지 인덱스를 기준으로 캐싱
- [x] 로딩 화면 주입
- ~~H-Genuine 단계 `isAvailable` 데이터로 비활성화 옵션 필터링~~
- [x] 각 단계에서 선택한 데이터 `MakingCarViewModel`에 기록
    - [x] 트림 선택 기록
    - [x] 색상 선택 기록
    - [x] 선택 옵션 기록
- [x] 화면 진행에 따른 선택 인덱스 초기화
    - [x] 트림 선택 초기화
    - [x] 색상 선택 초기화
    - [x] 선택 옵션 초기화
