### ISSUE TITLE
[FE] 옵션 페이지 API 연동 및 페이지별 선택 옵션에 조건 반영

### ISSUE THREAD

**Issue by sukam09** [softeerbootcamp-2nd/H9-88Hey#136]
# 🕹️ 기능 설명
- 옵션 페이지에 API를 연동한다.
- 각각 H Genuine Accessories, N Performance 페이지 선택 옵션에 대하여 아래와 같은 조건을 반영한다.
  - H Genuine Accessories: 앞에서 선택한 옵션에 따라서 선택할 수 없는 경우는 blur 처리해서 비활성화한다.
  - N Performance: 한 가지 옵션만 선택할 수 있도록 한다.
- 기타 UI/UX를 개선한다.

# 📌 TO-DO
- [x] 옵션 페이지에 API 연동
- [x] 선택할 수 없는 경우는 blur 처리해서 비활성화
- [x] 한 가지 옵션만 선택할 수 있도록 변경
- [x] 옵션 카드 상세 설명에 스크롤 추가
- [x] H Genuine Accessories 페이지에 접근시 URL에 쿼리 스트링 추가
- [x] 옵션 카드 호버 시 스크롤로 변경
- [x] 서브옵션 설명과 모달 설명 -/br인 경우 예외처리 
- [x] H Genuine Accessories가 선택되었을 때 선택 옵션 변경하면 모달이 뜨고 초기화 버튼 누르면 H Genuine Accessories가 초기화되게 구현 
- ~~옵션 카드 상세 설명 제목 길어지면 폰트 사이즈 축소~~ DB에서 길이가 긴 제목 잘라서 해결
