### ISSUE TITLE
[BE] 아카이빙 조회 기능 구현

### ISSUE THREAD

**Issue by ddingmin** [softeerbootcamp-2nd/H9-88Hey#137]
# 🕹️ 기능 설명
- 옵션들을 선택하면 교집합 형태로 해당하는 아카이빙을 조회한다.

# 📌 TO-DO
- [x] 선택한 옵션에 따라 아카이빙들을 조회한다.
- [x] 페이지 네이션을 구현한다.
- [ ] 테스트 코드를 작성한다.
