### ISSUE TITLE
[AND] Navigation 구조 개선

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#144]
# ✏️ 계획 설명
* `내차만들기` 관련 컴포넌트들이 같은 Scope를 갖도록 `NavHost`를 추가 생성한다.

# 📌 TO-DO
- [x] `내차만들기` `NavHost` 선언
- [x] `MakingCarViewModel`이 `MainActivity`를 `ViewModelStoreOwner`로 갖지 않도록 변경
- [x] 데이터 로드까지 로드 이미지 송출
