### ISSUE TITLE
[AND] 내차만들기 UI 디테일 보완

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#147]
# 🕹️ 기능 설명
* 내차만들기 디자인에서 누락된 컴포넌트를 추가한다.

# 📌 TO-DO
- [ ] 360도 이미지 아래에 발판 이미지 넣기
- [ ] 선택옵션 아이템 UI 변경
    - [ ] 버튼 아래로 밀리는 상황
    - [ ] 배경색은 `animatedColorAsState` 제거
    - [ ] 완성화면 선택 옵션 텍스트 밀리는 상황
- [ ] `HorizontalPager` 구조 변경 (카드를 슬라이드 하지말고 카드 내부를 슬라이드)
