### ISSUE TITLE
[FE] 색상 페이지 이미지 최적화 및 마이카이빙 API 연동

### ISSUE THREAD

**Issue by lee-yun-pyo** [softeerbootcamp-2nd/H9-88Hey#172]
# 🕹️ 기능 설명
1. 색상 페이지에서 360도 구현에 사용될 이미지를 로딩할 때 끊기는 문제를 해결한다. 
2. 360도 구현에 사용될 60 x n 장의 이미지를 최적화하여 사용자 경험을 향상시킨다.
3. 마이카이빙 페이지 API 연동한다.

# 📌 TO-DO
- [x] 여러 이미지 최적화 방법을 공부하여 프로젝트의 적합한 방법을 찾는다.
- [x] 찾은 방법으로 이미지 최적화를 수행한다.
- [x] 마이카이빙 API 연동
