### ISSUE TITLE
[BE] 태그 조회 기능 구현

### ISSUE THREAD

**Issue by ddingmin** [softeerbootcamp-2nd/H9-88Hey#173]
# 🕹️ 기능 설명
- 내 차 만들기 페이지에서 태그 조회 기능을 구현한다.

# 📌 TO-DO
- [x] 색상 페이지에서 태그 조회 기능을 구현한다.
- [x] 색상 페이지에서 태그 조회 기능 테스트를 작성한다.
- [x] 선택 옵션 페이지에서 태그 조회 기능을 구현한다.
- [x] 선택 옵션 페이지에서 태그 조회 기능 테스트를 작성한다.
