### ISSUE TITLE
[FE] 내 차 만들기 선택옵션 common 컴포넌트 구현

### ISSUE THREAD

**Issue by sukam09** [softeerbootcamp-2nd/H9-88Hey#20]
# 🕹️ 기능 설명
- SelectOptionImageBox.tsx
    - props: image, 나머진 미정
- SelectOptionDescription.tsx
    - props: title, price, tags
- SelectOptionDetail.tsx
    - props: title, description
- OptionCardContainer.tsx
    - props: optionType
    - SelectOptionCard.tsx
        - props: selectedOptions, optionsData, onClick
    - DefaultOptionCard.tsx
        - props: optionsData

# 📌 TO-DO
- [x] SelectOptionImageBox 컴포넌트 구현
- [x] SelectOptionDescription 컴포넌트 구현
- [x] SelectOptionDetail 컴포넌트 구현
- [x] OptionCategory 컴포넌트 구현
- [x] SelectOptionCard 컴포넌트 구현
- [x] DefaultOptionCard 컴포넌트 구현
