### ISSUE TITLE
[AND] QA 피드백 반영

### ISSUE THREAD

**Issue by SeungWoo-Ahn** [softeerbootcamp-2nd/H9-88Hey#217]
# ✏️ 계획 설명
* QA 피드백을 반영해 UI와 로직을 개선한다

# 📌 TO-DO
- [x] 내 차 만들기 컴포넌트 `UI 개선`
- [x] 내 차 만들기 `로직 추가 및 변경`
- [x] 아카이빙 컴포넌트 `UI 개선`
- [x] 마이카이빙 컴포넌트 `UI 개선`
