### ISSUE TITLE
[AND] 아카이빙 바텀바 - 내차만들기 연동

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#220]
# 🕹️ 기능 설명
* 아카이빙 상세화면에서 사용되는 `BottomBar`의 미구현부를 보완하여 완성도를 높인다.

# 📌 TO-DO
- [x] `BottomBar`에 총 가격 연동
- [x] 버튼 클릭 시 `내차만들기`로 이동시키기
    - [x] `모델선택` 연동하기
    - [x] `트림옵션` 연동하기
    - [x] `색상선택` 연동하기
    - [x] `선택옵션` 연동하기
    - [x] `견적요약보기`와도 동기화
