### ISSUE TITLE
[AND] 트림 선택 확장

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#222]
# 🕹️ 기능 설명
* 르블랑 이외의 모델도 선택할 수 있도록 변경

# 📌 TO-DO
- [x] 트림 선택 첫화면 동적인 UI로 변경
- [x] 선택 옵션 필터링
- [x] 각종 네트워크 요청 메소드 리팩토링
