### ISSUE TITLE
[FE] 내 차 만들기 옵션선택 페이지 구현

### ISSUE THREAD

**Issue by sukam09** [softeerbootcamp-2nd/H9-88Hey#25]
# 🕹️ 기능 설명
내 차 만들기 옵션선택 페이지를 구현한다.
핵심 시나리오부터 먼저 구현하고 추가 기능은 나중으로 구현하는 것을 원칙으로 한다.

# 📌 TO-DO
## 리팩토링
- [x] 모든 데이터 pages 폴더 컴포넌트로 분리
- [x] 절대경로 alias @에서 @/로 변경
- [x] 여러 컴포넌트에서 사용하는 interface를 types 폴더로 분리
- [x] 컴포넌트명 좀 더 용도에 맞게 변경
- [x] 템플릿 폴더 지우고 페이지 폴더에 있는 컴포넌트로 대체
- [x] state 하단으로 내려서 props drilling 없애기
## 기능 구현
-  [x] 내 차 만들기 옵션선택 페이지 - 선택 항목
-  [x] 내 차 만들기 옵션선택 페이지 - 기본 포함 품목
