### ISSUE TITLE
[FE] 사용자명 아카이빙/마이카이빙 헤더에 추가 및 기타 UI 조정

### ISSUE THREAD

**Issue by sukam09** [softeerbootcamp-2nd/H9-88Hey#252]
# 🕹️ 기능 설명
사용자명을 아카이빙/마이카이빙 헤더에 추가하고 기타 UI를 조정한다.

# 📌 TO-DO
- [x] 헤더 팰리세이드 텍스트 색상 다른 텍스트와 일치하는 검은색으로 변경
- [x] 아카이빙/마이카이빙 페이지 헤더에 사용자명 추가
- [x] 아카이빙/마이카이빙 페이지 헤더에 로그아웃 버튼 추가
