### ISSUE TITLE
[AND] 로그인과 상태 관리 리팩터링

### ISSUE THREAD

**Issue by SeungWoo-Ahn** [softeerbootcamp-2nd/H9-88Hey#269]
# ✏️ 계획 설명
* 로그인 관리 코드를 리팩터링한다
* 상태 관리 코드를 리팩터링한다

# 📌 TO-DO
- [x] 로그인 리팩터링
- [x] 상태 관리 리팩터링
    - [x] 로그인 상태 관리 리팩터링
    - [x] 아카이빙 상태 관리 리팩터링
