### ISSUE TITLE
[BE] MySQL 접속 세팅

### ISSUE THREAD

**Issue by ddingmin** [softeerbootcamp-2nd/H9-88Hey#37]
# 🕹️ 기능 설명
- 스프링 프로젝트에서 MySQL을 연결한다.
- 내 차 만들기 서비스에 필요한 데이터를 데이터 베이스에 삽입한다.

# 📌 TO-DO
- [x] 스프링 프로젝트에서 MySQL을 연결한다.
- [x] JDBC 의존성 추가
- [x] 접속 테스트
- [x] CICD 를 위한 DB 설정파일 세팅
