### ISSUE TITLE
[BE] 내 차 만들기 기본옵션, 선택옵션 데이터 수집

### ISSUE THREAD

**Issue by RecordOfJun** [softeerbootcamp-2nd/H9-88Hey#46]
# 📌 TO-DO
- [x] 펠리세이드 기본 옵션 데이터 수집 및 삽입
- [x] 펠리세이드 선택옵션 및 하위옵션 데이터 수집 및 삽입
- [x] 트림, 엔진, 구동방식, 시트에 따른 선택옵션 매핑정보 삽입
