### ISSUE TITLE
[FE] 옵션 선택 페이지 마무리

### ISSUE THREAD

**Issue by sukam09** [softeerbootcamp-2nd/H9-88Hey#49]
# 🕹️ 기능 설명
내 차 만들기 옵션 선택 페이지에 대하여 마무리 작업을 진행한다.

# 📌 TO-DO
- [x] 기본 옵션 카드 리스트 컴포넌트를 옵션 페이지 컴포넌트로부터 분리
- [x] 옵션 카드 클릭 및 호버 범위를 버튼 위 영역만 해당하게끔 조정
- [x] 기본 옵션 카드 클릭했을 때 나오는 모달 구현
- [x] 옵션 카드 선택 정보를 footer와 local storage에 연결
- [x] MSW와 useFetch 사용해서 mock API 사용하도록 변경
- [ ] 로컬 이미지를 현대닷컴에 있는 이미지 링크로 교체
