### ISSUE TITLE
[AND] 내차만들기 화면 기본 구성

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#50]
# 🕹️ 기능 설명
* `Composable` Screen 영역에 공용 UI 컴포넌트를 호출해서 내차만들기 화면을 구성한다.

# 📌 TO-DO
- [x] 중첩 Navigation 구성
- [x] 트림선택 첫화면 구성
- [x] 트림선택 엔진-바디타입-구동방식 화면 구성
- [x] 색상선택 외장색상-내장색상 화면 구성
- [x] 옵션선택 선택옵션-HGenuine-NPerformance 화면 구성
- [x] 완성화면 구성
