### ISSUE TITLE
[FE] 색상 선택 페이지 마무리

### ISSUE THREAD

**Issue by lee-yun-pyo** [softeerbootcamp-2nd/H9-88Hey#52]
# 🕹️ 기능 설명
색상 선택 페이지 마무리 한다. 

# 📌 TO-DO
- [x] 색상 페이지 UI 수정
- [x] Footer에 데이터 적용
- [x] msw fetch 사용
