### ISSUE TITLE
[FE] 옵션 페이지 유지보수 및 완성 페이지 UI 제작

### ISSUE THREAD

**Issue by sukam09** [softeerbootcamp-2nd/H9-88Hey#66]
# 🕹️ 기능 설명
옵션 페이지의 이미지가 제대로 표시되지 않는 문제나 footer에 가격이 반영되지 않는 문제 등 여러 사항을 수정하고 내 차 만들기 완성 페이지의 UI를 제작한다.

# 📌 TO-DO
- [x] 이미지 경로를 현대닷컴에 있는 이미지로 교체
- [x] H Genuine Accessories 페이지 구현
- [x] N Performance 페이지 구현
- [x] 내 차 만들기 완성 페이지 UI 구현
- [x] 선택 옵션 정보 footer 가격에 반영
