### ISSUE TITLE
[AND] 견적 요약 보기 및 기본 포함 품목 구현 (BottomSheet)

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#79]
# 🕹️ 기능 설명
* `BottomSheet`로 호출되는 견적 요약 보기 및 기본 포함 품목을 구현한다.

# 📌 TO-DO
- [x] 견적 요약 보기 상태 관리
- [x] 기본 포함 품목 `BottomSheet` 구현
- [x] 아카이빙 검색 `BottomSheet` 구현
