### ISSUE TITLE
[AND] State holder 선언 및 리팩토링

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#80]
# 🕹️ 기능 설명
* 기존 state 관리 로직을 수정하고 각종 state holder에 상태 변수를 선언한다.

# 📌 TO-DO
- [x] `AppState`에 UI elements' State 변수 선언
- [x] `ViewModel`에 Screen UI State 선언
- [x] `ProgressBar` state holder 리팩토링
- [x] Top/BottomBar 분기 리팩토링
