### ISSUE TITLE
[BE] CI 빌드 테스트 구축

### ISSUE THREAD

**Issue by ddingmin** [softeerbootcamp-2nd/H9-88Hey#89]
# 🕹️ 설명
- 실제 DB 서버와 동일한 CI 테스트 환경을 구축하여 PR시 자동으로 테스트 하도록 한다.

# 📌 TO-DO
- [ ] Github Action에 실제 DB와 동일한 MySQL 환경을 구성한다.
- [ ] 테스트 MySQL DB에 실제 DB와 동일한 테이블과 데이터를 세팅한다.
- [ ] PR을 생성할 때 실행되며, 테스트가 통과해야 머지하도록 세팅한다.
