### ISSUE TITLE
[AND] 내차만들기 네트워크 연결

### ISSUE THREAD

**Issue by TTC1018** [softeerbootcamp-2nd/H9-88Hey#92]
# 🕹️ 기능 설명
* 내차만들기를 구성하는 화면에 더미 데이터 대신 네트워크 데이터를 송출한다.

# 📌 TO-DO
- [x] 모델 선택 데이터 네트워크에서 내려받아 출력
- [x] 트림 선택 데이터 네트워크에서 내려받아 출력
- [x] 색상 선택 데이터 네트워크에서 내려받아 출력
- [x] 옵션 선택 데이터 네트워크에서 내려받아 출력
